global:
  scrape_interval: 15s
  external_labels:
    monitor: "docker-monitor"
  scrape_interval: 60s
  external_labels:
    monitor: "frontend"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
rule_files:
  - "alert.rules"
